# На примере HH

In [ ]:
pip install -U requests

In [1]:
import requests

import pandas as pd

In [25]:
url = 'https://api.hh.ru/vacancies'

text = 'аналитик данных'

In [26]:
parameters = {
    'vacancy_search_fields': 'name',#ищем текст только в названии вакансии
    'text': text,#сам текст
    'area': '113',# номер региона
    'per_page': '10',# 10 найденных вакансий с текстом, который мы ищем, будет нам отображаться за 1 запрос к серверу(т.е. Сколько вакансий отображать на одной странице (в ответе API))
    'page': 1,# вывести всю 2 страницу с названиями вакансий, так как нумерация начинается с нуля
    'responses_count_enabled': True, #включить отображение количества откликов на каждую вакансию (если API это поддерживает)
}

In [28]:
vacancies_info = r.json()

In [ ]:
vacancies_info

In [7]:
df = pd.DataFrame({
    'id':[],
    'name':[],
    'salary':[],
    'company':[],
    'url': []
})

In [ ]:
for vac in vacancies_info['items']:# по всем найденным вакансиям
    vac_parser = { # создается новый словарь
        'id': vac['id'],
        'name': vac['name'],
        'salary': vac['salary'],
        'company': vac['employer']['name'],#vac['employer']['name'] — это доступ к полю 'name' внутри вложенного словаря 'employer'
        'url': vac['url']
    }
    df.loc[len(df)] = vac_parser#Это способ добавить или изменить строку в таблице. Если строки с таким индексом ещё нет — она создаётся. Если уже есть — заменяется.

In [11]:
df

,id,name,salary,company,url
0,122082014,Директор административно-кадровой службы,None,Благотворительный Фонд Владимира Потанина,https://api.hh.ru/vacancies/122082014?host=hh.ru
1,118855620,Маркетолог-аналитик,"{'from': None, 'to': 110000, 'currency': 'RUR'...","ПАРИ, АО Страховая компания",https://api.hh.ru/vacancies/118855620?host=hh.ru
2,122098717,Операционный менеджер (Экономист),"{'from': 80000, 'to': 80000, 'currency': 'RUR'...",ВОЛМА,https://api.hh.ru/vacancies/122098717?host=hh.ru
3,121404690,Аналитик,"{'from': 110000, 'to': 110000, 'currency': 'RU...",International Tobacco Group,https://api.hh.ru/vacancies/121404690?host=hh.ru
4,121877405,Менеджер маркетплейсов (книги),"{'from': 90000, 'to': 120000, 'currency': 'RUR...",Издательский Дом Филипок и К,https://api.hh.ru/vacancies/121877405?host=hh.ru
5,121720203,Аналитик данных,"{'from': 100000, 'to': None, 'currency': 'RUR'...",Айтиспортс,https://api.hh.ru/vacancies/121720203?host=hh.ru
6,121971573,Инженер по тестированию,None,Банк ПСБ,https://api.hh.ru/vacancies/121971573?host=hh.ru
7,122066391,Руководитель отдела продаж / Sales Director,None,Lotus,https://api.hh.ru/vacancies/122066391?host=hh.ru
8,122058416,Project Manager (помощник руководителя проектн...,"{'from': 300000, 'to': None, 'currency': 'RUR'...",Топассистент,https://api.hh.ru/vacancies/122058416?host=hh.ru
9,121743051,Менеджер по работе с маркетплейсами,None,АПС-СПб,https://api.hh.ru/vacancies/121743051?host=hh.ru

# Парсинг с помощью BeautifulSoup

Beautiful Soup - это библиотека для Python, которая позволяет парсить (анализировать) HTML и XML документы. Она предоставляет удобный способ искать, навигировать(ориентирорваться, перемещаться), и модифицировать дерево DOM (Document Object Model), представляющее HTML/XML документ.

In [ ]:
%pip install -U beautifulsoup4

In [12]:
from bs4 import BeautifulSoup

In [13]:
url = 'http://quotes.toscrape.com/'

In [14]:
r = requests.get(url, verify=False, timeout=10)
#Этот код на Python использует библиотеку requests для выполнения HTTP-запроса типа GET к указанному url. Разберем его подробнее:

#requests.get(url, ...) — выполняет HTTP-запрос GET по адресу, указанному в переменной url.
#verify=False — отключает проверку SSL-сертификата(SSL-сертификат - это цифровой сертификат, который подтверждает подлинность веб-сайта и обеспечивает безопасное соединение между браузером пользователя и сервером). Это небезопасно и может привести к уязвимостям (например, MITM-атакам).
#timeout=10 — устанавливает максимальное время ожидания ответа в 10 секунд. Если сервер не ответит за это время, вызов вызовет исключение requests.exceptions.Timeout.
r

In [15]:
soup = BeautifulSoup(r.content, 'html.parser')#Этот код использует библиотеку BeautifulSoup для парсинга HTML-ответа, полученного при выполнении HTTP-запроса. Разберем его подробнее:

#r.content — это тело ответа от сервера, которое содержится в объекте r (скорее всего, это результат запроса через requests.get()). В отличие от r.text, которое возвращает ответ в виде строки, r.content предоставляет байтовые данные, что важно, если контент может быть в другом формате (например, изображение или файл).
#BeautifulSoup(r.content, 'html.parser') — создает объект BeautifulSoup для парсинга HTML-кода, переданного в виде байтов. 'html.parser' указывает, что для парсинга будет использован стандартный парсер HTML, встроенный в Python.
#Что происходит в итоге:
#Этот код создает объект soup, который представляет собой структурированное дерево HTML-страницы, и с помощью него можно легко извлекать элементы, искать теги, атрибуты и т. д.

In [16]:
print(soup.prettify())#означает:"Выведи HTML-код красиво и удобно для чтения человеком."

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Quotes to Scrape
  </title>
  <link href="/static/bootstrap.min.css" rel="stylesheet"/>
  <link href="/static/main.css" rel="stylesheet"/>
 </head>
 <body>
  <div class="container">
   <div class="row header-box">
    <div class="col-md-8">
     <h1>
      <a href="/" style="text-decoration: none">
       Quotes to Scrape
      </a>
     </h1>
    </div>
    <div class="col-md-4">
     <p>
      <a href="/login">
       Login
      </a>
     </p>
    </div>
   </div>
   <div class="row">
    <div class="col-md-8">
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
       <a class="tag" href="/tag/change/page/1/">
        change
       </a>
       <a class="tag" href="/tag/deep-thoughts/page/1/">
        deep-thoughts
       </a>
       <a class="tag" href="/tag/thinking/page/1/">
        thinking
       </a>
       <a class="tag" href="/tag/world/page/1/">
        world
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “It is our choices, Harry, that show what we truly are, far more than our abilities.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        J.K. Rowling
       </small>
       <a href="/author/J-K-Rowling">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
       <a class="tag" href="/tag/abilities/page/1/">
        abilities
       </a>
       <a class="tag" href="/tag/choices/page/1/">
        choices
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
       <a class="tag" href="/tag/life/page/1/">
        life
       </a>
       <a class="tag" href="/tag/live/page/1/">
        live
       </a>
       <a class="tag" href="/tag/miracle/page/1/">
        miracle
       </a>
       <a class="tag" href="/tag/miracles/page/1/">
        miracles
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Jane Austen
       </small>
       <a href="/author/Jane-Austen">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
       <a class="tag" href="/tag/aliteracy/page/1/">
        aliteracy
       </a>
       <a class="tag" href="/tag/books/page/1/">
        books
       </a>
       <a class="tag" href="/tag/classic/page/1/">
        classic
       </a>
       <a class="tag" href="/tag/humor/page/1/">
        humor
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Marilyn Monroe
       </small>
       <a href="/author/Marilyn-Monroe">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
       <a class="tag" href="/tag/be-yourself/page/1/">
        be-yourself
       </a>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “Try not to become a man of success. Rather become a man of value.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
       <a class="tag" href="/tag/adulthood/page/1/">
        adulthood
       </a>
       <a class="tag" href="/tag/success/page/1/">
        success
       </a>
       <a class="tag" href="/tag/value/page/1/">
        value
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “It is better to be hated for what you are than to be loved for what you are not.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        André Gide
       </small>
       <a href="/author/Andre-Gide">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="life,love" itemprop="keywords"/>
       <a class="tag" href="/tag/life/page/1/">
        life
       </a>
       <a class="tag" href="/tag/love/page/1/">
        love
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “I have not failed. I've just found 10,000 ways that won't work.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Thomas A. Edison
       </small>
       <a href="/author/Thomas-A-Edison">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
       <a class="tag" href="/tag/edison/page/1/">
        edison
       </a>
       <a class="tag" href="/tag/failure/page/1/">
        failure
       </a>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
       <a class="tag" href="/tag/paraphrased/page/1/">
        paraphrased
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “A woman is like a tea bag; you never know how strong it is until it's in hot water.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Eleanor Roosevelt
       </small>
       <a href="/author/Eleanor-Roosevelt">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
       <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">
        misattributed-eleanor-roosevelt
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “A day without sunshine is like, you know, night.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Steve Martin
       </small>
       <a href="/author/Steve-Martin">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
       <a class="tag" href="/tag/humor/page/1/">
        humor
       </a>
       <a class="tag" href="/tag/obvious/page/1/">
        obvious
       </a>
       <a class="tag" href="/tag/simile/page/1/">
        simile
       </a>
      </div>
     </div>
     <nav>
      <ul class="pager">
       <li class="next">
        <a href="/page/2/">
         Next
         <span aria-hidden="true">
          →
         </span>
        </a>
       </li>
      </ul>
     </nav>
    </div>
    <div class="col-md-4 tags-box">
     <h2>
      Top Ten tags
     </h2>
     <span class="tag-item">
      <a class="tag" href="/tag/love/" style="font-size: 28px">
       love
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/inspirational/" style="font-size: 26px">
       inspirational
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/life/" style="font-size: 26px">
       life
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/humor/" style="font-size: 24px">
       humor
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/books/" style="font-size: 22px">
       books
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/reading/" style="font-size: 14px">
       reading
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/friendship/" style="font-size: 10px">
       friendship
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/friends/" style="font-size: 8px">
       friends
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/truth/" style="font-size: 8px">
       truth
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/simile/" style="font-size: 6px">
       simile
      </a>
     </span>
    </div>
   </div>
  </div>
  <footer class="footer">
   <div class="container">
    <p class="text-muted">
     Quotes by:
     <a href="https://www.goodreads.com/quotes">
      GoodReads.com
     </a>
    </p>
    <p class="copyright">
     Made with
     <span class="zyte">
      ❤
     </span>
     by
     <a class="zyte" href="https://www.zyte.com">
      Zyte
     </a>
    </p>
   </div>
  </footer>
 </body>
</html>

In [17]:
divs = soup.find_all('div', attrs={'class':'quote'})#Эта строка ищет все теги <div> с классом quote на HTML-странице и сохраняет их в список divs

In [18]:
df = pd.DataFrame({
    'text':[],
    'author':[],
    'author_url':[],
    'tags':[],
})

In [19]:
def get_quotes(soup, data=df):#data=df означает, что если при вызове функции get_quotes не передать значение для data, то по умолчанию оно будет равно df
    
    divs = soup.find_all('div', attrs={'class':'quote'})
    
    for div in divs:
        quote = {}
        quote['text'] = div.find('span', class_='text').text
        quote['author'] = div.find('small', class_='author').text
        quote['author_url'] = div.find_all('span')[1].find('a').get('href')#Этот код находит ссылку на страницу автора цитаты и сохраняет её в словарь.
        tags = []
        for a_tag in div.find('div', class_='tags').find_all('a', class_='tag'):#Внутри блока с цитатой ищем все слова с классом 'tag' и сохраняем их в список tags
            tags.append(a_tag.text)
        quote['tags'] = ', '.join(tags)
        df.loc[len(df)] = quote #Добавляет словарь quote как новую строку в таблицу df

In [20]:
url = 'https://quotes.toscrape.com/page/'

for i in range(1, 21):
    print(f'Page N:{i}')
    r = requests.get(url + str(i), timeout=10)
    soup = BeautifulSoup(r.content, 'html.parser')
    
    get_quotes(soup, df)
    
    if 'No quotes found!' in soup.text:
        break

Page N:1
Page N:2
Page N:3
Page N:4
Page N:5
Page N:6
Page N:7
Page N:8
Page N:9
Page N:10
Page N:11

In [21]:
df.tail()

,text,author,author_url,tags
95,“You never really understand a person until yo...,Harper Lee,/author/Harper-Lee,better-life-empathy
96,“You have to write the book that wants to be w...,Madeleine L'Engle,/author/Madeleine-LEngle,"books, children, difficult, grown-ups, write, ..."
97,“Never tell the truth to people who are not wo...,Mark Twain,/author/Mark-Twain,truth
98,"“A person's a person, no matter how small.”",Dr. Seuss,/author/Dr-Seuss,inspirational
99,“... a mind needs books as a sword needs a whe...,George R.R. Martin,/author/George-R-R-Martin,"books, mind"

In [22]:
df

,text,author,author_url,tags
0,“The world as we have created it is a process ...,Albert Einstein,/author/Albert-Einstein,"change, deep-thoughts, thinking, world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,/author/J-K-Rowling,"abilities, choices"
2,“There are only two ways to live your life. On...,Albert Einstein,/author/Albert-Einstein,"inspirational, life, live, miracle, miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,/author/Jane-Austen,"aliteracy, books, classic, humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself, inspirational"
...,...,...,...,...
95,“You never really understand a person until yo...,Harper Lee,/author/Harper-Lee,better-life-empathy
96,“You have to write the book that wants to be w...,Madeleine L'Engle,/author/Madeleine-LEngle,"books, children, difficult, grown-ups, write, ..."
97,“Never tell the truth to people who are not wo...,Mark Twain,/author/Mark-Twain,truth
98,"“A person's a person, no matter how small.”",Dr. Seuss,/author/Dr-Seuss,inspirational
99,“... a mind needs books as a sword needs a whe...,George R.R. Martin,/author/George-R-R-Martin,"books, mind"